name: Build All Database Versions

on:
  push:
    branches:
      - '**'  # Run on all branches
  workflow_dispatch:  # Allow manual trigger

jobs:
  list-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    
    - name: Get versions and set matrix
      id: set-matrix
      shell: bash
      run: |
        # Get all versions and format as a matrix
        VERSIONS=$(opendpm list --json)
        # Convert to proper GitHub Actions matrix format
        echo "matrix={\"includes\":$VERSIONS}" >> $GITHUB_OUTPUT
  
  build-versions:
    needs: list-versions
    strategy:
      matrix: ${{ fromJson(needs.list-versions.outputs.matrix) }}
      # Allow other versions to build even if one fails
      fail-fast: false
    
    uses: ./.github/workflows/build-database.yml
    with:
      version_id: ${{ matrix.id }}
