name: Release Databases

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:  # Allow manual trigger

env:
  INPUT_DIR: data/input
  OUTPUT_DIR: data/output

jobs:
  build:
    uses: ./.github/workflows/build-database.yml
  
  create-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download SQLite artifacts
      uses: actions/download-artifact@v4
      with:
        name: databases-sqlite
        path: databases-sqlite
    
    - name: Download DuckDB artifacts
      uses: actions/download-artifact@v4
      with:
        name: databases-duckdb
        path: databases-duckdb
    
    - name: Zip SQLite database files
      run: |
        cd databases-sqlite
        zip -r ../dpm-sqlite.zip *
        cd ..
    
    - name: Zip DuckDB database files
      run: |
        cd databases-duckdb
        zip -r ../dpm-duckdb.zip *
        cd ..
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: "Release ${{ github.ref_name }}"
        prerelease: true
        generate_release_notes: true
        files: |
          dpm-sqlite.zip
          dpm-duckdb.zip
