name: Release Databases

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:  # Allow manual trigger

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version_id: ${{ steps.get-latest-version.outputs.version_id }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e src/.
    
    - name: Get latest version
      id: get-latest-version
      shell: bash
      run: |
        # Get latest version ID
        echo "version_id=$(opendpm list --latest --json | jq '.id')" >> $GITHUB_OUTPUT

  build:
    needs: get-version
    uses: ./.github/workflows/build-database.yml
    with:
      version_id: ${{ needs.get-version.outputs.version_id }}
  
  create-release:
    needs: [get-version, build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download SQLite artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.get-version.outputs.version_id }}
        path: .

    - name: Zip SQLite database
      run: |
        zip dpm-sqlite.zip dpm.sqlite
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: "Release ${{ needs.get-version.outputs.version_id }}"
        prerelease: false
        generate_release_notes: true
        files: |
          dpm-sqlite.zip
          *.py
