name: Build All Database Versions

on:
  push:
    branches:
      - '**'  # Run on all branches
  workflow_dispatch:  # Allow manual trigger

jobs:
  list-versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.get-versions.outputs.versions }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    
    - name: Get all available versions
      id: get-versions
      shell: bash
      run: |
        # Get all versions as a JSON array
        VERSIONS=$(opendpm list --json)
        # Format as a JSON string for GitHub Actions output
        echo "versions=$VERSIONS" >> $GITHUB_OUTPUT
  
  build-versions:
    needs: list-versions
    strategy:
      matrix:
        version: ${{ fromJson(needs.list-versions.outputs.versions) }}
      # Allow other versions to build even if one fails
      fail-fast: false
    
    uses: ./.github/workflows/build-database.yml
    with:
      version_id: ${{ matrix.version.id }}
