name: Release Databases

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:  # Allow manual trigger

env:
  INPUT_DIR: data/input
  OUTPUT_DIR: data/output

jobs:
  build:
    uses: ./.github/workflows/build-database.yml
  
  create-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: databases
        path: ${{ env.OUTPUT_DIR }}
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: "Release ${{ github.ref_name }}"
        generate_release_notes: true
        files: ${{ env.OUTPUT_DIR }}/*
