name: Upload Databases

on:
  push:
    branches:
      - '**'  # Run on all branches
    tags-ignore:
      - 'v*'  # Ignore version tags
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    uses: ./.github/workflows/build-database.yml
