name: Release Databases

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:  # Allow manual trigger

env:
  INPUT_DIR: data/input
  OUTPUT_DIR: data/output

jobs:
  build:
    uses: ./.github/workflows/build-database.yml
  
  create-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download SQLite database artifact
      uses: actions/download-artifact@v4
      with:
        name: dpm-sqlite-db
        path: .
    
    - name: Download models artifact
      uses: actions/download-artifact@v4
      with:
        name: dpm-models
        path: .
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: "Release ${{ github.ref_name }}"
        prerelease: false
        generate_release_notes: true
        files: |
          dpm-sqlite.zip
          dpm_models.py
