name: Build All Database Versions

on:
  push:
    branches:
      - '**'  # Run on all branches
  workflow_dispatch:  # Allow manual trigger

jobs:
  list-versions:
    runs-on: ubuntu-latest
    outputs:
      version_ids: ${{ steps.set-matrix.outputs.version_ids }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    
    - name: Get versions and set matrix
      id: set-matrix
      shell: bash
      run: |
        echo test=$(opendpm list --json | jq 'map(.id)')
        echo test
        echo version_ids=$(opendpm list --json | jq 'map(.id)') >> $GITHUB_OUTPUT
  
  build-versions:
    needs: list-versions
    strategy:
      matrix: ${{ fromJson(needs.list-versions.outputs.version_ids) }}
      # Allow other versions to build even if one fails
      fail-fast: false
    
    uses: ./.github/workflows/build-database.yml
    with:
      version_id: ${{ matrix.version_id }}
