name: New download urls

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  get-new-download-urls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Run get-new-download-urls.sh
        run: bash .github/scripts/get-new-download-urls.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
