name: Run Type Checking

on:
  workflow_call:

env:
  ACCESS_ENGINE_INSTALLER: accessdatabaseengine_X64.exe
  ACCESS_ENGINE_URL: https://download.microsoft.com/download/3/5/C/35C84C36-661A-44E6-9324-8786B8DBE231/accessdatabaseengine_X64.exe
  ACCESS_ENGINE_SHA256: "04e96c9f1a1f7d251a88aececf1dc10ff65950392787427c00814a43308003de"

jobs:
  type-check:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    
    strategy:
      fail-fast: false
      matrix:
        type-checker:
          - name: MyPy
            command: mypy
            beta: false
          - name: Pyright
            command: pyright
            beta: false
          - name: Ty
            command: ty check
            beta: true
          - name: Pyrefly
            command: pyrefly
            beta: true
        project:
          - name: Main CLI
            path: src/
          - name: Archive Module
            path: projects/archive/src/
          - name: Compare Module
            path: projects/compare/src/
          - name: Schema Module
            path: projects/schema/src/
          - name: Scrape Module
            path: projects/scrape/src/
          - name: Migrate Module
            path: projects/migrate/src/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install UV
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Cache Access Database Engine
        id: cache-access-engine
        uses: actions/cache@v4
        with:
          path: ${{ env.ACCESS_ENGINE_INSTALLER }}
          key: access-engine-${{ env.ACCESS_ENGINE_SHA256 }}

      - name: Download Access Database Engine
        if: steps.cache-access-engine.outputs.cache-hit != 'true'
        shell: bash
        run: |
          curl -L --fail --retry 3 --retry-delay 5 "${{ env.ACCESS_ENGINE_URL }}" -o "${{ env.ACCESS_ENGINE_INSTALLER }}"

      - name: Verify file hash
        if: steps.cache-access-engine.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          $expectedHash = "${{ env.ACCESS_ENGINE_SHA256 }}"
          $actualHash = (Get-FileHash "${{ env.ACCESS_ENGINE_INSTALLER }}" -Algorithm SHA256).Hash.ToLower()

          if ($actualHash -ne $expectedHash.ToLower()) {
            Write-Error "Hash mismatch. Expected: $expectedHash, Got: $actualHash"
            exit 1
          }

      - name: Install Microsoft Access Database Engine
        shell: powershell
        run: |
          Start-Process -FilePath "${{ env.ACCESS_ENGINE_INSTALLER }}" -ArgumentList "/quiet" -Wait

      - name: Install dependencies
        run: |
          uv sync --dev
          # Install all dependencies including Windows-specific migrate
          uv sync --extra compare --extra schema --extra scrape --extra migrate

      - name: Run ${{ matrix.type-checker.name }} on ${{ matrix.project.name }}
        continue-on-error: ${{ matrix.type-checker.beta }}
        run: |
          echo "::group::${{ matrix.type-checker.name }}${{ matrix.type-checker.beta && ' (beta)' || '' }} - ${{ matrix.project.name }}"
          uv run ${{ matrix.type-checker.command }} ${{ matrix.project.path }}
          echo "::endgroup::"
