name: Test Database Conversion

on:
  workflow_dispatch:  # Allow manual trigger

jobs:
  test-conversion:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        
    - name: Run conversion process
      run: |
        python -m dpm.cli
    
    - name: Upload converted databases as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: converted-databases
        path: |
          .scratch/db_output/*.duckdb
          .scratch/db_output/*.sqlite
        if-no-files-found: error
