name: Test Database Conversion

on:
  workflow_dispatch:  # Allow manual trigger

jobs:
  test-conversion:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Cache Access Database Engine
      id: cache-access-db
      uses: actions/cache@v3
      with:
        path: AccessDatabaseEngine.exe
        key: access-db-engine-2016-x64

    - name: Download Microsoft Access Database Engine
      if: steps.cache-access-db.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        $url = "https://download.microsoft.com/download/3/5/C/35C84C36-661A-44E6-9324-8786B8DBE231/accessdatabaseengine_X64.exe"
        Invoke-WebRequest -Uri $url -OutFile "AccessDatabaseEngine.exe"

    - name: Install Microsoft Access Database Engine
      shell: powershell
      run: |
        Start-Process -FilePath "AccessDatabaseEngine.exe" -ArgumentList "/quiet" -Wait
    
    - name: Run conversion process
      run: |
        python -m dpm.cli
    
    - name: Upload converted databases as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: converted-databases
        path: |
          .scratch/db_output/*.duckdb
          .scratch/db_output/*.sqlite
        if-no-files-found: error
